
import Footer from './footer'
import styles from '../../styles/Home.module.css';
import Head from 'next/head';

export default function Layout({ children }) {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Car Tracker Simple Website</title>
                    <meta name="description" content="Simple Cars tracker website Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Welcome to Cars Tracker!
                    </h1>

                    <p className={styles.description}>
                        Simple Example and showcase for car tracker website.
                    </p>
                    {children}
                </main>
            </div>
            <Footer /></>

    )
}