import * as React from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import Map from '../../components/Map';

import Head from 'next/head'
import styles from '../../../styles/Home.module.css';
import dynamic from 'next/dynamic'

const DEFAULT_CENTER = [38.907132, -77.036546]

export default function map() {
  return (
      
    <div className={styles.container}>
    <Head>
      <title>Cars Tracker Example</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Cars Tracker!
        </h1>

        <p className={styles.description}>
          Simple Example and showcase for car tracker website.
        </p>
        <Map className={styles.homeMap} center={DEFAULT_CENTER} zoom={12}>
          {({ TileLayer, Marker, Popup }) => (
            <>
              <TileLayer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
              />
              <Marker position={DEFAULT_CENTER}>
                <Popup>
                  A pretty CSS3 popup. <br /> Easily customizable.
                </Popup>
              </Marker>
            </>
          )}
        </Map>

    </main>
    </div>
  );
}
